Bases exercice 10: gestion du depôt
simai-ml/how-to-opensource pull request #1
Opened 2021-06-14 14:38 UTC by dhervault

Bases exercice 10: gestion du depôt

2021-06-16 10:11 UTC, gmartinonQM requested changes

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Pour faciliter l'accessibilité du package, sa mise à disposition sur PiPy est un defacto standard. Nous allons donc ajouter à nos workflow d'intégration continue cette publication. Elle sera déclench
typo: est *defacto* un standard

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Pour faciliter l'accessibilité du package, sa mise à disposition sur PiPy est un defacto standard. Nous allons donc ajouter à nos workflow d'intégration continue cette publication. Elle sera déclench
typo: consommateurs

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Pour faciliter l'accessibilité du package, sa mise à disposition sur PiPy est un defacto standard. Nous allons donc ajouter à nos workflow d'intégration continue cette publication. Elle sera déclench
typo: contrôlant

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Dans la mesure où ce nom de version va se retrouver à plusieurs endroit (setup.py, doc/conf.py, ...), et pour ne pas risquer d'erreur dans le maintient en cohérence de cette information à plusieurs e
typo: endroits

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Dans la mesure où ce nom de version va se retrouver à plusieurs endroit (setup.py, doc/conf.py, ...), et pour ne pas risquer d'erreur dans le maintient en cohérence de cette information à plusieurs e
typo: risquer d'erreurs

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Dans la mesure où ce nom de version va se retrouver à plusieurs endroit (setup.py, doc/conf.py, ...), et pour ne pas risquer d'erreur dans le maintient en cohérence de cette information à plusieurs e
typo: dans le maintien

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Enfin il convient d'ajouter de documenter les régles de contribution et d'usage du package. Pour cela rendez vous dans la page **Insights/Community** de GitHub. Cette dernière fournit un moyen simple
typo: règles

2021-06-16 10:11 UTC, gmartinonQM commented on README.rst
> +Enfin il convient d'ajouter de documenter les régles de contribution et d'usage du package. Pour cela rendez vous dans la page **Insights/Community** de GitHub. Cette dernière fournit un moyen simple
typo: bien sûr

2021-06-16 10:11 UTC, gmartinonQM commented on doc/conf.py
> +release = '0.0.1'
attention, il y a une incohérence entre cette ligne et ce qui est paramétré dans .bumpversion.cfg

2021-06-16 15:43 UTC, dhervault commented on doc/conf.py
> +release = '0.0.1'
La valeur définie est partout à 0.0.1, dans:

-  setup.py
- _version.py
- doc/conf.py
- .bumpversion.cfg

c'est pas ce qu'il faut ?

2021-06-16 15:43 UTC, dhervault commented on README.rst
> +Enfin il convient d'ajouter de documenter les régles de contribution et d'usage du package. Pour cela rendez vous dans la page **Insights/Community** de GitHub. Cette dernière fournit un moyen simple
Done

2021-06-16 15:43 UTC, dhervault commented on README.rst
> +Dans la mesure où ce nom de version va se retrouver à plusieurs endroit (setup.py, doc/conf.py, ...), et pour ne pas risquer d'erreur dans le maintient en cohérence de cette information à plusieurs e
Done

2021-06-16 17:17 UTC, gmartinonQM commented on doc/conf.py
> +release = '0.0.1'
La valeur est bonne, mais ton fichier de conf chercher à faire des replace sur "version =" et pas sur "release ="

2021-06-17 07:52 UTC, dhervault commented on README.rst
> +Pour faciliter l'accessibilité du package, sa mise à disposition sur PiPy est un defacto standard. Nous allons donc ajouter à nos workflow d'intégration continue cette publication. Elle sera déclench
Done

2021-06-17 07:52 UTC, dhervault commented on doc/conf.py
> +release = '0.0.1'
Done

2021-06-17 07:57 UTC, merged